version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
      - cp server/harvest/config/settings.xml /root/.m2/settings.xml
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - pwd
      - ls -l
      - cd server/harvest
      - ls -l
      - echo now build
      - mvn package
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed o `date`
      - ls -l
      - pwd
artifacts:
  files:
    - server/harvest/target/harvest-ratings-1.0-SNAPSHOT.jar
    - server/aws/sam-app/sam-ratings.yml
  discard-paths: yes
secondary-artifacts:
  cf-config:
    files:
      - server/aws/sam-app/sam-ratings.yml
    discard-paths: yes
  jar-file:
    files:
      - server/harvest/target/harvest-ratings-1.0-SNAPSHOT.jar
    discard-paths: yes


