AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - uk.co.ameth::harvest-ratings
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Parameters:
  IosAppId:
    Type: String
    Default: 9999999
    Description: the number id of the iOS Application

Resources:
  HarvestRatingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: uk.co.ameth.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: build/harvest-ratings-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
      Environment:
        Variables:
          IOS_APP_KEY: !Ref IosAppId
  RatingsDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Review
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: "PROVISIONED"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
Outputs:
  HarvestRatingsApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: HarvestRatingsApi
