AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Serverless Spring Boot API - uk.co.ameth::harvest-ratings
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Outputs:
  HarvestReviewsApi:
    Description: URL for application
    Export:
      Name: HarvestReviewsApi
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
Parameters:
  AmazonAwsAccessKey:
    Type: String
  AmazonAwsSecretKey:
    Type: String
  AmazonDynamoDbEndpoint:
    Type: String
  IosAppId:
    Type: String
  IosUrl:
    Type: String
Resources:
  HarvestReviewsFunction:
    Properties:
      CodeUri: ./harvest-ratings-1.0-SNAPSHOT.jar
      Environment:
        Variables:
          AMAZON_AWS_ACCESS_KEY: !Ref 'AmazonAwsAccessKey'
          AMAZON_AWS_SECRET_KEY: !Ref 'AmazonAwsSecretKey'
          AMAZON_DYNAMO_DB_ENDPOINT: !Ref 'AmazonDynamoDbEndpoint'
          IOS_APP_ID: !Ref 'IosAppId'
          IOS_URL: !Ref 'IosUrl'
      Events:
        GetResource:
          Properties:
            Method: any
            Path: /{proxy+}
          Type: Api
      Handler: uk.co.ameth.StreamLambdaHandler::handleRequest
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Runtime: java8
      Timeout: 60
    Type: AWS::Serverless::Function
  ReviewsDbTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      BillingMode: PROVISIONED
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      TableName: Reviews
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
